window.FIELD_DICTIONARY = [
  {
    "id": 1,
    "col": "A",
    "section": "项目基本信息",
    "section_range": "A–K",
    "name_cn": "新、旧项目",
    "name_en": "New/Existing Project",
    "data_type": "分类",
    "source_type": "system_sync",
    "calc_logic": "系统判定是否为报告年度新增项目；平台同步新增默认为新项目；年末自动 rollover 为旧项目",
    "enum_values": [
      "新项目",
      "旧项目"
    ],
    "description": "工程平台引用列。系统判定是否为当年新增项目：正式上线后平台自动入库的项目默认为「新项目」；跨报告年度初全部 rollover 为「旧项目」。特殊情况可由系统管理员覆盖显示值（§2.2.2）。"
  },
  {
    "id": 2,
    "col": "B",
    "section": "项目基本信息",
    "section_range": "A–K",
    "name_cn": "约定开始时间",
    "name_en": "Contracted Start Date",
    "data_type": "日期",
    "source_type": "system_sync",
    "calc_logic": "",
    "enum_values": [],
    "description": "取自 CRB，只读。合同约定项目开始日期。"
  },
  {
    "id": 3,
    "col": "C",
    "section": "项目基本信息",
    "section_range": "A–K",
    "name_cn": "约定结束时间",
    "name_en": "Contracted End Date",
    "data_type": "日期",
    "source_type": "system_sync",
    "calc_logic": "",
    "enum_values": [],
    "description": "取自 CRB，只读。合同约定项目结束日期。"
  },
  {
    "id": 4,
    "col": "D",
    "section": "项目基本信息",
    "section_range": "A–K",
    "name_cn": "执行单位编码",
    "name_en": "Execution Unit Code",
    "data_type": "文本",
    "source_type": "system_sync",
    "calc_logic": "",
    "enum_values": [],
    "description": "取自 CRB，只读。负责执行项目的部门/单位编码。"
  },
  {
    "id": 5,
    "col": "E",
    "section": "项目基本信息",
    "section_range": "A–K",
    "name_cn": "项目经理",
    "name_en": "Project Manager",
    "data_type": "文本",
    "source_type": "system_sync",
    "calc_logic": "",
    "enum_values": [],
    "description": "取自 CRB。人员变更时需同步更新 CRB，前端显示最新数据。"
  },
  {
    "id": 6,
    "col": "F",
    "section": "项目基本信息",
    "section_range": "A–K",
    "name_cn": "项目号",
    "name_en": "Project No.",
    "data_type": "文本",
    "source_type": "system_sync",
    "calc_logic": "",
    "enum_values": [],
    "description": "取自 CRB，只读。项目唯一标识编号，作为主键使用。"
  },
  {
    "id": 7,
    "col": "G",
    "section": "项目基本信息",
    "section_range": "A–K",
    "name_cn": "项目名称",
    "name_en": "Project Name",
    "data_type": "文本",
    "source_type": "system_sync",
    "calc_logic": "",
    "enum_values": [],
    "description": "取自 CRB，只读。项目全称。"
  },
  {
    "id": 8,
    "col": "H",
    "section": "项目基本信息",
    "section_range": "A–K",
    "name_cn": "客户名称",
    "name_en": "Client Name",
    "data_type": "文本",
    "source_type": "system_sync",
    "calc_logic": "",
    "enum_values": [],
    "description": "取自 CRB，只读。甲方客户全称。"
  },
  {
    "id": 9,
    "col": "I",
    "section": "项目基本信息",
    "section_range": "A–K",
    "name_cn": "企业属性",
    "name_en": "Enterprise Type",
    "data_type": "分类",
    "source_type": "system_sync",
    "calc_logic": "",
    "enum_values": [],
    "description": "取自 CRB，只读。客户的企业性质分类（自由文本，非枚举约束）。"
  },
  {
    "id": 10,
    "col": "J",
    "section": "项目基本信息",
    "section_range": "A–K",
    "name_cn": "行业类别",
    "name_en": "Industry Category",
    "data_type": "分类",
    "source_type": "system_sync",
    "calc_logic": "",
    "enum_values": [],
    "description": "取自 CRB，只读。客户所属行业分类。"
  },
  {
    "id": 11,
    "col": "K",
    "section": "项目基本信息",
    "section_range": "A–K",
    "name_cn": "业务类型",
    "name_en": "Business Type",
    "data_type": "分类",
    "source_type": "system_sync",
    "calc_logic": "",
    "enum_values": [],
    "description": "取自 CRB，只读。项目所属业务类型分类。"
  },
  {
    "id": 12,
    "col": "L",
    "section": "合同签署与进展",
    "section_range": "L–M",
    "name_cn": "合同是否签署",
    "name_en": "Contract Signed",
    "data_type": "分类",
    "source_type": "auto_calc",
    "calc_logic": "取自CRB合同状态：CRB状态为「已确认」→显示「已签署」，否则→「未签署」",
    "enum_values": [
      "已签署",
      "未签署"
    ],
    "description": "系统自动判定：取自 CRB 合同状态。未签署项目需通过「提前申报产值」审批流程后，才会出现在追踪表中。"
  },
  {
    "id": 13,
    "col": "M",
    "section": "合同签署与进展",
    "section_range": "L–M",
    "name_cn": "项目实施进展",
    "name_en": "Implementation Progress",
    "data_type": "分类",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [
      "进行中",
      "已完成",
      "暂缓",
      "已终止"
    ],
    "description": "项目经理手工填报，反映项目当前实际物理进展状态。"
  },
  {
    "id": 14,
    "col": "N",
    "section": "合同额",
    "section_range": "N–Q",
    "name_cn": "截止上一年底合同额",
    "name_en": "Cut-off Previous Year",
    "data_type": "金额",
    "source_type": "system_sync",
    "calc_logic": "",
    "enum_values": [],
    "description": "系统锁定基准：每年 1 月 1 日自动封存上一年度的期末 CRB 数据。后台数据库永久记录历年快照，前端只读，不可更改。"
  },
  {
    "id": 15,
    "col": "O",
    "section": "合同额",
    "section_range": "N–Q",
    "name_cn": "当年调整值",
    "name_en": "Adjustment",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=P-N",
    "enum_values": [],
    "description": "总合同额与上一年底基准的差值，反映当年合同额相对于基准的变化量。"
  },
  {
    "id": 16,
    "col": "P",
    "section": "合同额",
    "section_range": "N–Q",
    "name_cn": "总合同额",
    "name_en": "Contract Value",
    "data_type": "金额",
    "source_type": "system_sync",
    "calc_logic": "",
    "enum_values": [],
    "description": "CRB 动态取数：未签署项目取 CRB1 合同额；签署后（状态变为「已确认」）自动切换取 CRB3 合同额。前端不可修改。"
  },
  {
    "id": 17,
    "col": "Q",
    "section": "合同额",
    "section_range": "N–Q",
    "name_cn": "不含税总合同额",
    "name_en": "Contract Value (excl. tax)",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=P/(1+Y)",
    "enum_values": [],
    "description": "总合同额去除税费，用于不含税口径统计。"
  },
  {
    "id": 18,
    "col": "R",
    "section": "存量指标",
    "section_range": "R–S",
    "name_cn": "存量开票额",
    "name_en": "Remaining Invoice Capacity",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=P-AC",
    "enum_values": [],
    "description": "总合同额减始累开票（P-AC）。正数表示尚未开票的合同部分；小于 0 时触发预警（累计开票已超过总合同额）。"
  },
  {
    "id": 19,
    "col": "S",
    "section": "存量指标",
    "section_range": "R–S",
    "name_cn": "存量合同额",
    "name_en": "Remaining Contract Capacity",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=P-U",
    "enum_values": [],
    "description": "总合同额减始累完成（P-U）。表示尚未完成的合同部分，不得为负；调增月度完成额时若将导致本列为负则禁止保存；提交前须调减至非负。"
  },
  {
    "id": 20,
    "col": "T",
    "section": "始累完成合同额",
    "section_range": "T–V",
    "name_cn": "截止上一年底始累完成",
    "name_en": "Cumulative Completed (Prev Year-End)",
    "data_type": "金额",
    "source_type": "system_sync",
    "calc_logic": "",
    "enum_values": [],
    "description": "系统自动翻转：每年 1 月 1 日抓取上一年度末累计完成值并锁定。后台保留每年历史快照。"
  },
  {
    "id": 21,
    "col": "U",
    "section": "始累完成合同额",
    "section_range": "T–V",
    "name_cn": "项目始累完成合同额",
    "name_en": "Project Cumulative Completed",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=T+X",
    "enum_values": [],
    "description": "上一年底始累完成 + 本年度完成，即项目从开始至今的累计完成额。"
  },
  {
    "id": 22,
    "col": "V",
    "section": "始累完成合同额",
    "section_range": "T–V",
    "name_cn": "当年期初存量",
    "name_en": "Opening Backlog (Current Year)",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=N-T",
    "enum_values": [],
    "description": "年初合同额基准与年初始累完成的差额，反映年初时尚未完成的合同存量。"
  },
  {
    "id": 23,
    "col": "W",
    "section": "年度完成额申报",
    "section_range": "W–Z",
    "name_cn": "报告当期完成",
    "name_en": "Current Period Completed",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=当月填报列（动态映射，如5月=AZ）",
    "enum_values": [],
    "description": "动态映射至当月填报列（AV~BG），随月份自动切换。报告当期的完成申报金额。"
  },
  {
    "id": 24,
    "col": "X",
    "section": "年度完成额申报",
    "section_range": "W–Z",
    "name_cn": "本年度完成",
    "name_en": "YTD Completed",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=SUM(AV~当月完成列)",
    "enum_values": [],
    "description": "本年1月至报告当月的各月完成额汇总，随填报数据动态更新。"
  },
  {
    "id": 25,
    "col": "Y",
    "section": "年度完成额申报",
    "section_range": "W–Z",
    "name_cn": "税率",
    "name_en": "Tax Rate",
    "data_type": "比率",
    "source_type": "system_sync",
    "calc_logic": "",
    "enum_values": [],
    "description": "取自 CRB 合同条款，系统同步。适用税率影响不含税金额计算（自由文本，非枚举约束）。"
  },
  {
    "id": 26,
    "col": "Z",
    "section": "年度完成额申报",
    "section_range": "W–Z",
    "name_cn": "不含税本年度完成",
    "name_en": "YTD Completed (excl. tax)",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=X/(1+Y)",
    "enum_values": [],
    "description": "本年度完成额去税，用于不含税口径统计汇总。"
  },
  {
    "id": 27,
    "col": "AA",
    "section": "开票回款情况",
    "section_range": "AA–AF",
    "name_cn": "截止上一年底累计开票",
    "name_en": "Cumulative Invoiced (Prev Year-End)",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "系统自动翻转：每年1月1日锁定上一年末累计开票值",
    "enum_values": [],
    "description": "系统自动翻转：每年 1 月 1 日抓取上一年度末累计开票并锁定。后台保留每年历史快照。"
  },
  {
    "id": 28,
    "col": "AB",
    "section": "开票回款情况",
    "section_range": "AA–AF",
    "name_cn": "本年累计开票",
    "name_en": "YTD Invoiced",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=SUM(BH,BJ,BL,BN,BP,BR,BT,BV,BX,BZ,CB,CD)",
    "enum_values": [],
    "description": "本年1月至报告当月的各月开票金额汇总。"
  },
  {
    "id": 29,
    "col": "AC",
    "section": "开票回款情况",
    "section_range": "AA–AF",
    "name_cn": "项目始累开票",
    "name_en": "Project Cumulative Invoiced",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=AA+AB",
    "enum_values": [],
    "description": "上一年底累计开票 + 本年累计开票，即项目从开始至今的累计开票总额。"
  },
  {
    "id": 30,
    "col": "AD",
    "section": "开票回款情况",
    "section_range": "AA–AF",
    "name_cn": "截止上一年底累计回款",
    "name_en": "Cumulative Received (Prev Year-End)",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "系统自动翻转：每年1月1日锁定上一年末累计回款值",
    "enum_values": [],
    "description": "系统自动翻转：每年 1 月 1 日抓取上一年度末累计回款并锁定。后台保留每年历史快照。"
  },
  {
    "id": 31,
    "col": "AE",
    "section": "开票回款情况",
    "section_range": "AA–AF",
    "name_cn": "本年累计回款",
    "name_en": "YTD Received",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=SUM(BI,BK,BM,BO,BQ,BS,BU,BW,BY,CA,CC,CE)",
    "enum_values": [],
    "description": "本年1月至报告当月的各月回款金额汇总。"
  },
  {
    "id": 32,
    "col": "AF",
    "section": "开票回款情况",
    "section_range": "AA–AF",
    "name_cn": "项目始累回款",
    "name_en": "Project Cumulative Received",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=AD+AE",
    "enum_values": [],
    "description": "上一年底累计回款 + 本年累计回款，即项目从开始至今的累计回款总额。"
  },
  {
    "id": 33,
    "col": "AG",
    "section": "财务数据（WIP/应收）",
    "section_range": "AG–AI",
    "name_cn": "WIP（含税）",
    "name_en": "WIP (incl. tax)",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=U-AC",
    "enum_values": [],
    "description": "已完工未开票金额（含税），反映项目的工程在产品余额。"
  },
  {
    "id": 34,
    "col": "AH",
    "section": "财务数据（WIP/应收）",
    "section_range": "AG–AI",
    "name_cn": "WIP（不含税）",
    "name_en": "WIP (excl. tax)",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=AG/(1+Y)",
    "enum_values": [],
    "description": "WIP 含税金额去税后的不含税值，用于不含税口径汇总。"
  },
  {
    "id": 35,
    "col": "AI",
    "section": "财务数据（WIP/应收）",
    "section_range": "AG–AI",
    "name_cn": "应收账款（含预收）",
    "name_en": "Accounts Receivable (incl. advances)",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=AC-AF",
    "enum_values": [],
    "description": "已开票未回款金额。正数为应收账款，负数表示客户已预付（预收账款）。"
  },
  {
    "id": 36,
    "col": "AJ",
    "section": "应收账款及WIP",
    "section_range": "AJ–AL",
    "name_cn": "应收账款（催收）",
    "name_en": "AR for Collection",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=MAX(AI,0)",
    "enum_values": [],
    "description": "取 AI 的正数部分，即实际需要催收的应收账款金额（排除预收场景）。"
  },
  {
    "id": 37,
    "col": "AK",
    "section": "应收账款及WIP",
    "section_range": "AJ–AL",
    "name_cn": "期初应收账款",
    "name_en": "Opening AR",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=MAX(AA-AD,0)",
    "enum_values": [],
    "description": "年初时的应收账款余额，取上一年底累计开票与累计回款之差的正数部分。"
  },
  {
    "id": 38,
    "col": "AL",
    "section": "应收账款及WIP",
    "section_range": "AJ–AL",
    "name_cn": "WIP（催开票）",
    "name_en": "WIP Pending Invoice",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=MAX(AG,0)",
    "enum_values": [],
    "description": "取 AG 的正数部分，即实际需要催开票的 WIP 金额（排除异常场景）。"
  },
  {
    "id": 39,
    "col": "AM",
    "section": "WIP分析与措施",
    "section_range": "AM–AU",
    "name_cn": "WIP形成原因",
    "name_en": "WIP Cause Category",
    "data_type": "分类",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [
      "A、到了付款节点应付未付所形成的WIP",
      "B、单价合同未到付款节点所形成的WIP",
      "C、总价合同未到付款节点所形成的WIP",
      "D、其它原因"
    ],
    "description": "项目经理手工填报，下拉选择与 Excel 一致的 WIP 形成原因（A/B/C/D）。"
  },
  {
    "id": 40,
    "col": "AN",
    "section": "WIP分析与措施",
    "section_range": "AM–AU",
    "name_cn": "原因说明",
    "name_en": "Cause Description",
    "data_type": "文本",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "配合 AM 原因分类，填写详细的原因说明文字。"
  },
  {
    "id": 41,
    "col": "AO",
    "section": "WIP分析与措施",
    "section_range": "AM–AU",
    "name_cn": "高风险WIP",
    "name_en": "High-Risk WIP Flag",
    "data_type": "布尔",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [
      "是",
      "否"
    ],
    "description": "项目经理或板块管理员标记是否为高风险 WIP，影响风险预警显示。"
  },
  {
    "id": 42,
    "col": "AP",
    "section": "WIP分析与措施",
    "section_range": "AM–AU",
    "name_cn": "期初WIP",
    "name_en": "Opening WIP",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "=MAX(T-AA,0)",
    "enum_values": [],
    "description": "年初时的 WIP 余额，取上一年底始累完成与累计开票之差的正数部分。"
  },
  {
    "id": 43,
    "col": "AQ",
    "section": "WIP分析与措施",
    "section_range": "AM–AU",
    "name_cn": "3个月以上WIP",
    "name_en": "WIP > 3 Months",
    "data_type": "金额",
    "source_type": "auto_calc",
    "calc_logic": "逻辑计算：对比近3个月申报产值与当前WIP，判断账龄超过3个月的WIP金额",
    "enum_values": [],
    "description": "系统根据近3个月月度产值申报数据与 WIP 余额，计算账龄超过3个月的 WIP 部分。"
  },
  {
    "id": 44,
    "col": "AR",
    "section": "WIP分析与措施",
    "section_range": "AM–AU",
    "name_cn": "修正后3个月WIP",
    "name_en": "Adjusted WIP > 3M",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "允许项目经理对系统计算的3个月以上WIP进行人工微调修正，填写修正后的实际金额。"
  },
  {
    "id": 45,
    "col": "AS",
    "section": "WIP分析与措施",
    "section_range": "AM–AU",
    "name_cn": "因素分析",
    "name_en": "Factor Analysis",
    "data_type": "文本",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "对 WIP 形成和变动的详细因素分析文字说明。"
  },
  {
    "id": 46,
    "col": "AT",
    "section": "WIP分析与措施",
    "section_range": "AM–AU",
    "name_cn": "拟采取行动",
    "name_en": "Planned Actions",
    "data_type": "文本",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "拟采取的催开票、催收款等行动计划的文字描述。"
  },
  {
    "id": 47,
    "col": "AU",
    "section": "WIP分析与措施",
    "section_range": "AM–AU",
    "name_cn": "预测开票时间",
    "name_en": "Projected Invoice Date",
    "data_type": "日期",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "项目经理预测的下次开票时间节点，选择未来月份。"
  },
  {
    "id": 48,
    "col": "AV",
    "section": "完成额统计与预测",
    "section_range": "AV–BG",
    "name_cn": "1月完成额",
    "name_en": "Jan Completed",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度完成合同额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 49,
    "col": "AW",
    "section": "完成额统计与预测",
    "section_range": "AV–BG",
    "name_cn": "2月完成额",
    "name_en": "Feb Completed",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度完成合同额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 50,
    "col": "AX",
    "section": "完成额统计与预测",
    "section_range": "AV–BG",
    "name_cn": "3月完成额",
    "name_en": "Mar Completed",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度完成合同额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 51,
    "col": "AY",
    "section": "完成额统计与预测",
    "section_range": "AV–BG",
    "name_cn": "4月完成额",
    "name_en": "Apr Completed",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度完成合同额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 52,
    "col": "AZ",
    "section": "完成额统计与预测",
    "section_range": "AV–BG",
    "name_cn": "5月完成额",
    "name_en": "May Completed",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度完成合同额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 53,
    "col": "BA",
    "section": "完成额统计与预测",
    "section_range": "AV–BG",
    "name_cn": "6月完成额",
    "name_en": "Jun Completed",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度完成合同额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 54,
    "col": "BB",
    "section": "完成额统计与预测",
    "section_range": "AV–BG",
    "name_cn": "7月完成额",
    "name_en": "Jul Completed",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度完成合同额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 55,
    "col": "BC",
    "section": "完成额统计与预测",
    "section_range": "AV–BG",
    "name_cn": "8月完成额",
    "name_en": "Aug Completed",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度完成合同额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 56,
    "col": "BD",
    "section": "完成额统计与预测",
    "section_range": "AV–BG",
    "name_cn": "9月完成额",
    "name_en": "Sep Completed",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度完成合同额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 57,
    "col": "BE",
    "section": "完成额统计与预测",
    "section_range": "AV–BG",
    "name_cn": "10月完成额",
    "name_en": "Oct Completed",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度完成合同额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 58,
    "col": "BF",
    "section": "完成额统计与预测",
    "section_range": "AV–BG",
    "name_cn": "11月完成额",
    "name_en": "Nov Completed",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度完成合同额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 59,
    "col": "BG",
    "section": "完成额统计与预测",
    "section_range": "AV–BG",
    "name_cn": "12月完成额",
    "name_en": "Dec Completed",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度完成合同额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 60,
    "col": "BH",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "1月开票",
    "name_en": "Jan Invoiced",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度开票金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 61,
    "col": "BI",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "1月回款",
    "name_en": "Jan Received",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度回款金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 62,
    "col": "BJ",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "2月开票",
    "name_en": "Feb Invoiced",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度开票金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 63,
    "col": "BK",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "2月回款",
    "name_en": "Feb Received",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度回款金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 64,
    "col": "BL",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "3月开票",
    "name_en": "Mar Invoiced",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度开票金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 65,
    "col": "BM",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "3月回款",
    "name_en": "Mar Received",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度回款金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 66,
    "col": "BN",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "4月开票",
    "name_en": "Apr Invoiced",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度开票金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 67,
    "col": "BO",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "4月回款",
    "name_en": "Apr Received",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度回款金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 68,
    "col": "BP",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "5月开票",
    "name_en": "May Invoiced",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度开票金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 69,
    "col": "BQ",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "5月回款",
    "name_en": "May Received",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度回款金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 70,
    "col": "BR",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "6月开票",
    "name_en": "Jun Invoiced",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度开票金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 71,
    "col": "BS",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "6月回款",
    "name_en": "Jun Received",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度回款金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 72,
    "col": "BT",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "7月开票",
    "name_en": "Jul Invoiced",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度开票金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 73,
    "col": "BU",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "7月回款",
    "name_en": "Jul Received",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度回款金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 74,
    "col": "BV",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "8月开票",
    "name_en": "Aug Invoiced",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度开票金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 75,
    "col": "BW",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "8月回款",
    "name_en": "Aug Received",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度回款金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 76,
    "col": "BX",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "9月开票",
    "name_en": "Sep Invoiced",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度开票金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 77,
    "col": "BY",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "9月回款",
    "name_en": "Sep Received",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度回款金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 78,
    "col": "BZ",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "10月开票",
    "name_en": "Oct Invoiced",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度开票金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 79,
    "col": "CA",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "10月回款",
    "name_en": "Oct Received",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度回款金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 80,
    "col": "CB",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "11月开票",
    "name_en": "Nov Invoiced",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度开票金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 81,
    "col": "CC",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "11月回款",
    "name_en": "Nov Received",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度回款金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 82,
    "col": "CD",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "12月开票",
    "name_en": "Dec Invoiced",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度开票金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  },
  {
    "id": 83,
    "col": "CE",
    "section": "开票与回款统计预测",
    "section_range": "BH–CE",
    "name_cn": "12月回款",
    "name_en": "Dec Received",
    "data_type": "金额",
    "source_type": "manual_input",
    "calc_logic": "",
    "enum_values": [],
    "description": "月度回款金额，手工填报。过去月份为历史数据，未来月份为预测数据。"
  }
];
